/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Esper.Config;
import Events.BreverageNumber;
import java.awt.*;
import javax.swing.*;
import java.io.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
/**
 *
 * @author user
 */
public class CoffieMachineView extends javax.swing.JFrame {

    /**
     * Creates new form CoffieMachineView
     */
    public CoffieMachineView() {
        initComponents();
        
    }
    public JTextField getCurrentTempTxt() {
        return currentTempTxt;
    }

    public JTextField getCurrentTempTxt1() {
        return currentTempTxt1;
    }

    public JButton getOffBtn() {
        return Start;
    }

    public JButton getOnBtn() {
        return Cancel;
    }
    public JButton getCappcation(){
        return Cappuccino;
    }
     public JButton getEspresso(){
        return Espresso;
    }
    public JButton getMacchiato(){
        return Macchiato;
    }
     public JButton getSuger_Shot(){
        return Suger_Shot;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Macchiato = new javax.swing.JButton();
        Start = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        currentTempTxt = new javax.swing.JTextField();
        currentTempTxt1 = new javax.swing.JTextField();
        Cappuccino = new javax.swing.JButton();
        Espresso = new javax.swing.JButton();
        Suger_Shot = new javax.swing.JButton();
        Caffe_Shot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Macchiato.setText("Macchiato");
        Macchiato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacchiatoActionPerformed(evt);
            }
        });

        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        currentTempTxt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        currentTempTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currentTempTxt.setEnabled(false);
        currentTempTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentTempTxtActionPerformed(evt);
            }
        });

        currentTempTxt1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        currentTempTxt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currentTempTxt1.setText("20");
        currentTempTxt1.setEnabled(false);
        currentTempTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentTempTxt1ActionPerformed(evt);
            }
        });

        Cappuccino.setText("Cappuccino");
        Cappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CappuccinoActionPerformed(evt);
            }
        });

        Espresso.setText("Espresso");
        Espresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspressoActionPerformed(evt);
            }
        });

        Suger_Shot.setText("Suger Shot");
        Suger_Shot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suger_ShotActionPerformed(evt);
            }
        });

        Caffe_Shot.setText("Caffe Shot");
        Caffe_Shot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caffe_ShotActionPerformed(evt);
            }
        });

        jLabel1.setText("WaterTemp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentTempTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(currentTempTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(156, 156, 156)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Caffe_Shot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Macchiato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cappuccino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Espresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Suger_Shot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(Macchiato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cappuccino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Espresso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Suger_Shot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Start)
                            .addComponent(Cancel)
                            .addComponent(Caffe_Shot))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentTempTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentTempTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MacchiatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacchiatoActionPerformed
        Config.sendEvent(new BreverageNumber(1));
    }//GEN-LAST:event_MacchiatoActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        Config.sendEvent(new BreverageNumber(6));    }//GEN-LAST:event_StartActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        Config.sendEvent(new BreverageNumber(5));
    }//GEN-LAST:event_CancelActionPerformed

    private void currentTempTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentTempTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentTempTxtActionPerformed

    private void CappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CappuccinoActionPerformed
        Config.sendEvent(new BreverageNumber(2));
    }//GEN-LAST:event_CappuccinoActionPerformed

    private void EspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspressoActionPerformed
       Config.sendEvent(new BreverageNumber(3));
    }//GEN-LAST:event_EspressoActionPerformed

    private void Suger_ShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suger_ShotActionPerformed
       Config.sendEvent(new BreverageNumber(4));
    }//GEN-LAST:event_Suger_ShotActionPerformed

    private void Caffe_ShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caffe_ShotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Caffe_ShotActionPerformed

    private void currentTempTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentTempTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentTempTxt1ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Caffe_Shot;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Cappuccino;
    private javax.swing.JButton Espresso;
    private javax.swing.JButton Macchiato;
    private javax.swing.JButton Start;
    private javax.swing.JButton Suger_Shot;
    private javax.swing.JTextField currentTempTxt;
    private javax.swing.JTextField currentTempTxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
